-- Schema completo para ChancePro - Base de datos Supabase
-- Generado automáticamente desde Django migrations

-- Migración: 0001_initial
BEGIN;
--
-- Create model Usuario
--
CREATE TABLE "core_usuario" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "documento" varchar(20) NOT NULL UNIQUE, "nombres" varchar(100) NOT NULL, "apellidos" varchar(100) NOT NULL, "direccion" text NOT NULL, "telefono" varchar(20) NOT NULL, "telefono_familiar" varchar(20) NOT NULL, "observaciones" text NOT NULL, "email" varchar(254) NULL, "rol" varchar(20) NOT NULL, "activo" boolean NOT NULL, "requiere_activacion" boolean NOT NULL, "fecha_afiliacion" date NULL, "fecha_vencimiento" date NULL, "configuracion" jsonb NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "empresario_id" bigint NULL);
CREATE TABLE "core_usuario_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usuario_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "core_usuario_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usuario_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model Apuesta
--
CREATE TABLE "core_apuesta" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "fecha_hora" timestamp with time zone NOT NULL, "numero" varchar(6) NOT NULL, "cifras" smallint NOT NULL CHECK ("cifras" >= 0), "monto_apostado" numeric(12, 2) NOT NULL, "premio_potencial" numeric(12, 2) NOT NULL, "estado" varchar(10) NOT NULL, "created_at" timestamp with time zone NOT NULL, "chancero_id" bigint NOT NULL, "empresario_id" bigint NOT NULL);
--
-- Create model Loteria
--
CREATE TABLE "core_loteria" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar(100) NOT NULL, "dias_habilitados" jsonb NOT NULL, "hora_apertura" time NOT NULL, "hora_cierre" time NOT NULL, "activa" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "empresario_id" bigint NOT NULL);
--
-- Create model Mensaje
--
CREATE TABLE "core_mensaje" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "telefono_destino" varchar(20) NOT NULL, "contenido" text NOT NULL, "tipo" varchar(10) NOT NULL, "fecha_hora_envio" timestamp with time zone NOT NULL, "apuesta_id" bigint NULL, "chancero_id" bigint NOT NULL, "empresario_id" bigint NOT NULL);
--
-- Create model Liquidacion
--
CREATE TABLE "core_liquidacion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "fecha_inicio" date NOT NULL, "fecha_fin" date NOT NULL, "total_ventas" numeric(12, 2) NOT NULL, "comision_porcentaje" numeric(5, 2) NOT NULL, "comision_valor" numeric(12, 2) NOT NULL, "estado" varchar(10) NOT NULL, "fecha_solicitud" timestamp with time zone NOT NULL, "fecha_pago" timestamp with time zone NULL, "chancero_id" bigint NOT NULL, "empresario_id" bigint NOT NULL);
--
-- Create model FacturaComision
--
CREATE TABLE "core_facturacomision" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "fecha_inicio" date NOT NULL, "fecha_fin" date NOT NULL, "total_ventas" numeric(12, 2) NOT NULL, "porcentaje_comision" numeric(5, 2) NOT NULL, "valor_comision" numeric(12, 2) NOT NULL, "estado" varchar(10) NOT NULL, "fecha_generacion" timestamp with time zone NOT NULL, "fecha_pago" timestamp with time zone NULL, "empresario_id" bigint NOT NULL);
--
-- Create model ComisionGlobal
--
CREATE TABLE "core_comisionglobal" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "porcentaje" numeric(5, 2) NOT NULL, "activo" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "empresario_id" bigint NOT NULL);
--
-- Add field loteria to apuesta
--
ALTER TABLE "core_apuesta" ADD COLUMN "loteria_id" bigint NOT NULL CONSTRAINT "core_apuesta_loteria_id_210623fc_fk_core_loteria_id" REFERENCES "core_loteria"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "core_apuesta_loteria_id_210623fc_fk_core_loteria_id" IMMEDIATE;
--
-- Create model TopeNumero
--
CREATE TABLE "core_topenumero" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "tope_maximo" numeric(12, 2) NOT NULL, "acumulado_actual" numeric(12, 2) NOT NULL, "empresario_id" bigint NOT NULL, "loteria_id" bigint NOT NULL);
--
-- Create model PlanPremio
--
CREATE TABLE "core_planpremio" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "cifras" smallint NOT NULL CHECK ("cifras" >= 0), "multiplicador" numeric(10, 2) NOT NULL, "empresario_id" bigint NOT NULL, "loteria_id" bigint NOT NULL);
--
-- Create model ComisionVendedor
--
CREATE TABLE "core_comisionvendedor" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "porcentaje" numeric(5, 2) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "chancero_id" bigint NOT NULL, "empresario_id" bigint NOT NULL);
ALTER TABLE "core_usuario" ADD CONSTRAINT "core_usuario_empresario_id_611a32d7_fk_core_usuario_id" FOREIGN KEY ("empresario_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_usuario_documento_8cb6b356_like" ON "core_usuario" ("documento" varchar_pattern_ops);
CREATE INDEX "core_usuario_empresario_id_611a32d7" ON "core_usuario" ("empresario_id");
ALTER TABLE "core_usuario_groups" ADD CONSTRAINT "core_usuario_groups_usuario_id_group_id_bde3c750_uniq" UNIQUE ("usuario_id", "group_id");
ALTER TABLE "core_usuario_groups" ADD CONSTRAINT "core_usuario_groups_usuario_id_97385234_fk_core_usuario_id" FOREIGN KEY ("usuario_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_usuario_groups" ADD CONSTRAINT "core_usuario_groups_group_id_55312a9a_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_usuario_groups_usuario_id_97385234" ON "core_usuario_groups" ("usuario_id");
CREATE INDEX "core_usuario_groups_group_id_55312a9a" ON "core_usuario_groups" ("group_id");
ALTER TABLE "core_usuario_user_permissions" ADD CONSTRAINT "core_usuario_user_permis_usuario_id_permission_id_7a048d24_uniq" UNIQUE ("usuario_id", "permission_id");
ALTER TABLE "core_usuario_user_permissions" ADD CONSTRAINT "core_usuario_user_pe_usuario_id_ce4108a7_fk_core_usua" FOREIGN KEY ("usuario_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_usuario_user_permissions" ADD CONSTRAINT "core_usuario_user_pe_permission_id_7f881653_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_usuario_user_permissions_usuario_id_ce4108a7" ON "core_usuario_user_permissions" ("usuario_id");
CREATE INDEX "core_usuario_user_permissions_permission_id_7f881653" ON "core_usuario_user_permissions" ("permission_id");
ALTER TABLE "core_apuesta" ADD CONSTRAINT "core_apuesta_chancero_id_6bf38260_fk_core_usuario_id" FOREIGN KEY ("chancero_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_apuesta" ADD CONSTRAINT "core_apuesta_empresario_id_69d990b9_fk_core_usuario_id" FOREIGN KEY ("empresario_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_apuesta_chancero_id_6bf38260" ON "core_apuesta" ("chancero_id");
CREATE INDEX "core_apuesta_empresario_id_69d990b9" ON "core_apuesta" ("empresario_id");
ALTER TABLE "core_loteria" ADD CONSTRAINT "core_loteria_empresario_id_nombre_a044d6d6_uniq" UNIQUE ("empresario_id", "nombre");
ALTER TABLE "core_loteria" ADD CONSTRAINT "core_loteria_empresario_id_d7af63a4_fk_core_usuario_id" FOREIGN KEY ("empresario_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_loteria_empresario_id_d7af63a4" ON "core_loteria" ("empresario_id");
ALTER TABLE "core_mensaje" ADD CONSTRAINT "core_mensaje_apuesta_id_88a0d5af_fk_core_apuesta_id" FOREIGN KEY ("apuesta_id") REFERENCES "core_apuesta" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_mensaje" ADD CONSTRAINT "core_mensaje_chancero_id_81bc60a8_fk_core_usuario_id" FOREIGN KEY ("chancero_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_mensaje" ADD CONSTRAINT "core_mensaje_empresario_id_b16a6723_fk_core_usuario_id" FOREIGN KEY ("empresario_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_mensaje_apuesta_id_88a0d5af" ON "core_mensaje" ("apuesta_id");
CREATE INDEX "core_mensaje_chancero_id_81bc60a8" ON "core_mensaje" ("chancero_id");
CREATE INDEX "core_mensaje_empresario_id_b16a6723" ON "core_mensaje" ("empresario_id");
ALTER TABLE "core_liquidacion" ADD CONSTRAINT "core_liquidacion_chancero_id_9e3c7a09_fk_core_usuario_id" FOREIGN KEY ("chancero_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_liquidacion" ADD CONSTRAINT "core_liquidacion_empresario_id_53812450_fk_core_usuario_id" FOREIGN KEY ("empresario_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_liquidacion_chancero_id_9e3c7a09" ON "core_liquidacion" ("chancero_id");
CREATE INDEX "core_liquidacion_empresario_id_53812450" ON "core_liquidacion" ("empresario_id");
ALTER TABLE "core_facturacomision" ADD CONSTRAINT "core_facturacomision_empresario_id_60dcafd6_fk_core_usuario_id" FOREIGN KEY ("empresario_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_facturacomision_empresario_id_60dcafd6" ON "core_facturacomision" ("empresario_id");
ALTER TABLE "core_comisionglobal" ADD CONSTRAINT "core_comisionglobal_empresario_id_b236fe24_fk_core_usuario_id" FOREIGN KEY ("empresario_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_comisionglobal_empresario_id_b236fe24" ON "core_comisionglobal" ("empresario_id");
CREATE INDEX "core_apuesta_loteria_id_210623fc" ON "core_apuesta" ("loteria_id");
ALTER TABLE "core_topenumero" ADD CONSTRAINT "core_topenumero_empresario_id_loteria_id_340ae9c7_uniq" UNIQUE ("empresario_id", "loteria_id");
ALTER TABLE "core_topenumero" ADD CONSTRAINT "core_topenumero_empresario_id_5f36fe4f_fk_core_usuario_id" FOREIGN KEY ("empresario_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_topenumero" ADD CONSTRAINT "core_topenumero_loteria_id_f069fe54_fk_core_loteria_id" FOREIGN KEY ("loteria_id") REFERENCES "core_loteria" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_topenumero_empresario_id_5f36fe4f" ON "core_topenumero" ("empresario_id");
CREATE INDEX "core_topenumero_loteria_id_f069fe54" ON "core_topenumero" ("loteria_id");
ALTER TABLE "core_planpremio" ADD CONSTRAINT "core_planpremio_empresario_id_loteria_id_cifras_960fceb2_uniq" UNIQUE ("empresario_id", "loteria_id", "cifras");
ALTER TABLE "core_planpremio" ADD CONSTRAINT "core_planpremio_empresario_id_f1b91b9e_fk_core_usuario_id" FOREIGN KEY ("empresario_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_planpremio" ADD CONSTRAINT "core_planpremio_loteria_id_3a2caae1_fk_core_loteria_id" FOREIGN KEY ("loteria_id") REFERENCES "core_loteria" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_planpremio_empresario_id_f1b91b9e" ON "core_planpremio" ("empresario_id");
CREATE INDEX "core_planpremio_loteria_id_3a2caae1" ON "core_planpremio" ("loteria_id");
ALTER TABLE "core_comisionvendedor" ADD CONSTRAINT "core_comisionvendedor_empresario_id_chancero_id_c0c6e5f0_uniq" UNIQUE ("empresario_id", "chancero_id");
ALTER TABLE "core_comisionvendedor" ADD CONSTRAINT "core_comisionvendedor_chancero_id_2d3d0558_fk_core_usuario_id" FOREIGN KEY ("chancero_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_comisionvendedor" ADD CONSTRAINT "core_comisionvendedor_empresario_id_4750e80a_fk_core_usuario_id" FOREIGN KEY ("empresario_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_comisionvendedor_chancero_id_2d3d0558" ON "core_comisionvendedor" ("chancero_id");
CREATE INDEX "core_comisionvendedor_empresario_id_4750e80a" ON "core_comisionvendedor" ("empresario_id");
COMMIT;

-- Migración: 0002_usuario_cifras_maximas_usuario_cifras_minimas_and_more
BEGIN;
--
-- Add field cifras_maximas to usuario
--
ALTER TABLE "core_usuario" ADD COLUMN "cifras_maximas" smallint DEFAULT 6 NULL CHECK ("cifras_maximas" >= 0);
ALTER TABLE "core_usuario" ALTER COLUMN "cifras_maximas" DROP DEFAULT;
--
-- Add field cifras_minimas to usuario
--
ALTER TABLE "core_usuario" ADD COLUMN "cifras_minimas" smallint DEFAULT 2 NULL CHECK ("cifras_minimas" >= 0);
ALTER TABLE "core_usuario" ALTER COLUMN "cifras_minimas" DROP DEFAULT;
--
-- Add field limite_chanceros to usuario
--
ALTER TABLE "core_usuario" ADD COLUMN "limite_chanceros" smallint DEFAULT 10 NULL CHECK ("limite_chanceros" >= 0);
ALTER TABLE "core_usuario" ALTER COLUMN "limite_chanceros" DROP DEFAULT;
COMMIT;

-- Migración: 0003_apuesta_liquidacion_apuesta_liquidacion_pagada
BEGIN;
--
-- Add field liquidacion to apuesta
--
ALTER TABLE "core_apuesta" ADD COLUMN "liquidacion_id" bigint NULL CONSTRAINT "core_apuesta_liquidacion_id_c49c688a_fk_core_liquidacion_id" REFERENCES "core_liquidacion"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "core_apuesta_liquidacion_id_c49c688a_fk_core_liquidacion_id" IMMEDIATE;
--
-- Add field liquidacion_pagada to apuesta
--
ALTER TABLE "core_apuesta" ADD COLUMN "liquidacion_pagada" boolean DEFAULT false NOT NULL;
ALTER TABLE "core_apuesta" ALTER COLUMN "liquidacion_pagada" DROP DEFAULT;
CREATE INDEX "core_apuesta_liquidacion_id_c49c688a" ON "core_apuesta" ("liquidacion_id");
COMMIT;

-- Migración: 0004_resultadoloteria
BEGIN;
--
-- Create model ResultadoLoteria
--
CREATE TABLE "core_resultadoloteria" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "fecha" date NOT NULL, "numero_ganador" varchar(6) NOT NULL, "cifras" smallint NOT NULL CHECK ("cifras" >= 0), "created_at" timestamp with time zone NOT NULL, "creado_por_id" bigint NOT NULL, "loteria_id" bigint NOT NULL);
ALTER TABLE "core_resultadoloteria" ADD CONSTRAINT "core_resultadoloteria_loteria_id_fecha_numero__e62cdd92_uniq" UNIQUE ("loteria_id", "fecha", "numero_ganador");
ALTER TABLE "core_resultadoloteria" ADD CONSTRAINT "core_resultadoloteria_creado_por_id_3a2a4a64_fk_core_usuario_id" FOREIGN KEY ("creado_por_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_resultadoloteria" ADD CONSTRAINT "core_resultadoloteria_loteria_id_ce25a255_fk_core_loteria_id" FOREIGN KEY ("loteria_id") REFERENCES "core_loteria" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_resultadoloteria_creado_por_id_3a2a4a64" ON "core_resultadoloteria" ("creado_por_id");
CREATE INDEX "core_resultadoloteria_loteria_id_ce25a255" ON "core_resultadoloteria" ("loteria_id");
COMMIT;

-- Migración: 0005_loteria_tope_premio
BEGIN;
--
-- Add field tope_premio to loteria
--
ALTER TABLE "core_loteria" ADD COLUMN "tope_premio" numeric(15, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "core_loteria" ALTER COLUMN "tope_premio" DROP DEFAULT;
COMMIT;

-- Migración: 0007_remove_usuario_cifras_maximas_and_more
BEGIN;
--
-- Remove field cifras_maximas from usuario
--
ALTER TABLE "core_usuario" DROP COLUMN "cifras_maximas" CASCADE;
--
-- Remove field cifras_minimas from usuario
--
ALTER TABLE "core_usuario" DROP COLUMN "cifras_minimas" CASCADE;
--
-- Add field autorizar_2c_combinado to usuario
--
ALTER TABLE "core_usuario" ADD COLUMN "autorizar_2c_combinado" boolean DEFAULT true NOT NULL;
ALTER TABLE "core_usuario" ALTER COLUMN "autorizar_2c_combinado" DROP DEFAULT;
--
-- Add field autorizar_2c_directo to usuario
--
ALTER TABLE "core_usuario" ADD COLUMN "autorizar_2c_directo" boolean DEFAULT true NOT NULL;
ALTER TABLE "core_usuario" ALTER COLUMN "autorizar_2c_directo" DROP DEFAULT;
--
-- Add field autorizar_3c_combinado to usuario
--
ALTER TABLE "core_usuario" ADD COLUMN "autorizar_3c_combinado" boolean DEFAULT true NOT NULL;
ALTER TABLE "core_usuario" ALTER COLUMN "autorizar_3c_combinado" DROP DEFAULT;
--
-- Add field autorizar_3c_directo to usuario
--
ALTER TABLE "core_usuario" ADD COLUMN "autorizar_3c_directo" boolean DEFAULT true NOT NULL;
ALTER TABLE "core_usuario" ALTER COLUMN "autorizar_3c_directo" DROP DEFAULT;
--
-- Add field autorizar_4c_combinado to usuario
--
ALTER TABLE "core_usuario" ADD COLUMN "autorizar_4c_combinado" boolean DEFAULT true NOT NULL;
ALTER TABLE "core_usuario" ALTER COLUMN "autorizar_4c_combinado" DROP DEFAULT;
--
-- Add field autorizar_4c_directo to usuario
--
ALTER TABLE "core_usuario" ADD COLUMN "autorizar_4c_directo" boolean DEFAULT true NOT NULL;
ALTER TABLE "core_usuario" ALTER COLUMN "autorizar_4c_directo" DROP DEFAULT;
--
-- Add field autorizar_5c_combinado to usuario
--
ALTER TABLE "core_usuario" ADD COLUMN "autorizar_5c_combinado" boolean DEFAULT true NOT NULL;
ALTER TABLE "core_usuario" ALTER COLUMN "autorizar_5c_combinado" DROP DEFAULT;
--
-- Add field autorizar_5c_directo to usuario
--
ALTER TABLE "core_usuario" ADD COLUMN "autorizar_5c_directo" boolean DEFAULT true NOT NULL;
ALTER TABLE "core_usuario" ALTER COLUMN "autorizar_5c_directo" DROP DEFAULT;
--
-- Add field autorizar_6c_combinado to usuario
--
ALTER TABLE "core_usuario" ADD COLUMN "autorizar_6c_combinado" boolean DEFAULT true NOT NULL;
ALTER TABLE "core_usuario" ALTER COLUMN "autorizar_6c_combinado" DROP DEFAULT;
--
-- Add field autorizar_6c_directo to usuario
--
ALTER TABLE "core_usuario" ADD COLUMN "autorizar_6c_directo" boolean DEFAULT true NOT NULL;
ALTER TABLE "core_usuario" ALTER COLUMN "autorizar_6c_directo" DROP DEFAULT;
COMMIT;

-- Migración: 0009_acumuladonumero
BEGIN;
--
-- Create model AcumuladoNumero
--
CREATE TABLE "core_acumuladonumero" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "numero" varchar(6) NOT NULL, "cifras" smallint NOT NULL CHECK ("cifras" >= 0), "monto_acumulado" numeric(15, 2) NOT NULL, "fecha_ultima_apuesta" timestamp with time zone NOT NULL, "empresario_id" bigint NOT NULL, "loteria_id" bigint NOT NULL);
ALTER TABLE "core_acumuladonumero" ADD CONSTRAINT "core_acumuladonumero_empresario_id_loteria_id_86bba810_uniq" UNIQUE ("empresario_id", "loteria_id", "numero", "cifras");
ALTER TABLE "core_acumuladonumero" ADD CONSTRAINT "core_acumuladonumero_empresario_id_de65ac79_fk_core_usuario_id" FOREIGN KEY ("empresario_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_acumuladonumero" ADD CONSTRAINT "core_acumuladonumero_loteria_id_1bd2d67e_fk_core_loteria_id" FOREIGN KEY ("loteria_id") REFERENCES "core_loteria" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_acumuladonumero_empresario_id_de65ac79" ON "core_acumuladonumero" ("empresario_id");
CREATE INDEX "core_acumuladonumero_loteria_id_1bd2d67e" ON "core_acumuladonumero" ("loteria_id");
COMMIT;

-- Migración: 0010_usuario_dias_retencion_datos
BEGIN;
--
-- Add field dias_retencion_datos to usuario
--
ALTER TABLE "core_usuario" ADD COLUMN "dias_retencion_datos" smallint DEFAULT 90 NOT NULL CHECK ("dias_retencion_datos" >= 0);
ALTER TABLE "core_usuario" ALTER COLUMN "dias_retencion_datos" DROP DEFAULT;
COMMIT;

-- Migración: 0011_cliente_historialcliente_and_more
BEGIN;
--
-- Create model Cliente
--
CREATE TABLE "core_cliente" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar(100) NOT NULL, "telefono" varchar(20) NOT NULL UNIQUE, "direccion" text NOT NULL, "notas" text NOT NULL, "fecha_registro" timestamp with time zone NOT NULL, "activo" boolean NOT NULL, "chancero_id" bigint NOT NULL);
--
-- Create model HistorialCliente
--
CREATE TABLE "core_historialcliente" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "fecha_registro" timestamp with time zone NOT NULL, "apuesta_id" bigint NOT NULL, "cliente_id" bigint NOT NULL);
--
-- Create index core_client_chancer_d39643_idx on field(s) chancero, telefono of model cliente
--
CREATE INDEX "core_client_chancer_d39643_idx" ON "core_cliente" ("chancero_id", "telefono");
--
-- Create index core_client_activo_726b6f_idx on field(s) activo of model cliente
--
CREATE INDEX "core_client_activo_726b6f_idx" ON "core_cliente" ("activo");
ALTER TABLE "core_cliente" ADD CONSTRAINT "core_cliente_chancero_id_772ac3e1_fk_core_usuario_id" FOREIGN KEY ("chancero_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_cliente_telefono_a91ca6c5_like" ON "core_cliente" ("telefono" varchar_pattern_ops);
CREATE INDEX "core_cliente_chancero_id_772ac3e1" ON "core_cliente" ("chancero_id");
ALTER TABLE "core_historialcliente" ADD CONSTRAINT "core_historialcliente_apuesta_id_2f6ffd69_fk_core_apuesta_id" FOREIGN KEY ("apuesta_id") REFERENCES "core_apuesta" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_historialcliente" ADD CONSTRAINT "core_historialcliente_cliente_id_280ac986_fk_core_cliente_id" FOREIGN KEY ("cliente_id") REFERENCES "core_cliente" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_historialcliente_apuesta_id_2f6ffd69" ON "core_historialcliente" ("apuesta_id");
CREATE INDEX "core_historialcliente_cliente_id_280ac986" ON "core_historialcliente" ("cliente_id");
CREATE INDEX "core_histor_cliente_cb0688_idx" ON "core_historialcliente" ("cliente_id", "fecha_registro");
CREATE INDEX "core_histor_apuesta_b3b6e0_idx" ON "core_historialcliente" ("apuesta_id");
COMMIT;

-- Migración: 0012_pagopremio
BEGIN;
--
-- Create model PagoPremio
--
CREATE TABLE "core_pagopremio" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "monto_pagado" numeric(12, 2) NOT NULL, "fecha_pago" timestamp with time zone NOT NULL, "observaciones" text NULL, "apuesta_id" bigint NOT NULL, "pagado_por_id" bigint NOT NULL);
ALTER TABLE "core_pagopremio" ADD CONSTRAINT "core_pagopremio_apuesta_id_2111d9f9_fk_core_apuesta_id" FOREIGN KEY ("apuesta_id") REFERENCES "core_apuesta" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_pagopremio" ADD CONSTRAINT "core_pagopremio_pagado_por_id_bae3a5a0_fk_core_usuario_id" FOREIGN KEY ("pagado_por_id") REFERENCES "core_usuario" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_pagopremio_apuesta_id_2111d9f9" ON "core_pagopremio" ("apuesta_id");
CREATE INDEX "core_pagopremio_pagado_por_id_bae3a5a0" ON "core_pagopremio" ("pagado_por_id");
COMMIT;

-- Migración: 0013_liquidacion_valor_empresario
BEGIN;
--
-- Add field valor_empresario to liquidacion
--
ALTER TABLE "core_liquidacion" ADD COLUMN "valor_empresario" numeric(12, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "core_liquidacion" ALTER COLUMN "valor_empresario" DROP DEFAULT;
COMMIT;

