# Generated by Django 4.2.7 on 2026-03-23 20:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_familiar', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rol', models.CharField(choices=[('admin_general', 'Administrador General'), ('empresario', 'Empresario'), ('chancero', 'Chancero')], default='chancero', max_length=20)),
                ('activo', models.BooleanField(default=False)),
                ('requiere_activacion', models.BooleanField(default=True)),
                ('fecha_afiliacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresario', models.ForeignKey(blank=True, limit_choices_to={'rol': 'empresario'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chanceros', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=6)),
                ('cifras', models.PositiveSmallIntegerField()),
                ('monto_apostado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premio_potencial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='activa', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chancero', models.ForeignKey(limit_choices_to={'rol': 'chancero'}, on_delete=django.db.models.deletion.CASCADE, related_name='apuestas_chancero', to=settings.AUTH_USER_MODEL)),
                ('empresario', models.ForeignKey(limit_choices_to={'rol': 'empresario'}, on_delete=django.db.models.deletion.CASCADE, related_name='apuestas_empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apuesta',
                'verbose_name_plural': 'Apuestas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Loteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dias_habilitados', models.JSONField(default=list)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresario', models.ForeignKey(limit_choices_to={'rol': 'empresario'}, on_delete=django.db.models.deletion.CASCADE, related_name='loterias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lotería',
                'verbose_name_plural': 'Loterías',
                'unique_together': {('empresario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_destino', models.CharField(max_length=20)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=10)),
                ('fecha_hora_envio', models.DateTimeField(auto_now_add=True)),
                ('apuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='core.apuesta')),
                ('chancero', models.ForeignKey(limit_choices_to={'rol': 'chancero'}, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_chancero', to=settings.AUTH_USER_MODEL)),
                ('empresario', models.ForeignKey(limit_choices_to={'rol': 'empresario'}, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_ventas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comision_valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('chancero', models.ForeignKey(limit_choices_to={'rol': 'chancero'}, on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_chancero', to=settings.AUTH_USER_MODEL)),
                ('empresario', models.ForeignKey(limit_choices_to={'rol': 'empresario'}, on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_empresario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
            },
        ),
        migrations.CreateModel(
            name='FacturaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_ventas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_comision', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('empresario', models.ForeignKey(limit_choices_to={'rol': 'empresario'}, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura de Comisión',
                'verbose_name_plural': 'Facturas de Comisiones',
            },
        ),
        migrations.CreateModel(
            name='ComisionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresario', models.ForeignKey(limit_choices_to={'rol': 'empresario'}, on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_globales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comisión Global',
                'verbose_name_plural': 'Comisiones Globales',
            },
        ),
        migrations.AddField(
            model_name='apuesta',
            name='loteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas', to='core.loteria'),
        ),
        migrations.CreateModel(
            name='TopeNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tope_maximo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('acumulado_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('empresario', models.ForeignKey(limit_choices_to={'rol': 'empresario'}, on_delete=django.db.models.deletion.CASCADE, related_name='topes', to=settings.AUTH_USER_MODEL)),
                ('loteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topes', to='core.loteria')),
            ],
            options={
                'verbose_name': 'Tope por Lotería',
                'verbose_name_plural': 'Topes por Lotería',
                'unique_together': {('empresario', 'loteria')},
            },
        ),
        migrations.CreateModel(
            name='PlanPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cifras', models.PositiveSmallIntegerField()),
                ('multiplicador', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresario', models.ForeignKey(limit_choices_to={'rol': 'empresario'}, on_delete=django.db.models.deletion.CASCADE, related_name='planes_premio', to=settings.AUTH_USER_MODEL)),
                ('loteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_premio', to='core.loteria')),
            ],
            options={
                'verbose_name': 'Plan de Premio',
                'verbose_name_plural': 'Planes de Premio',
                'unique_together': {('empresario', 'loteria', 'cifras')},
            },
        ),
        migrations.CreateModel(
            name='ComisionVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chancero', models.ForeignKey(limit_choices_to={'rol': 'chancero'}, on_delete=django.db.models.deletion.CASCADE, related_name='comision', to=settings.AUTH_USER_MODEL)),
                ('empresario', models.ForeignKey(limit_choices_to={'rol': 'empresario'}, on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comisión de Vendedor',
                'verbose_name_plural': 'Comisiones de Vendedores',
                'unique_together': {('empresario', 'chancero')},
            },
        ),
    ]
