# Generated by Django 4.2.7 on 2026-05-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cifras_maximas',
            field=models.PositiveSmallIntegerField(blank=True, default=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cifras_minimas',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='limite_chanceros',
            field=models.PositiveSmallIntegerField(blank=True, default=10, null=True),
        ),
    ]
