# Generated by Django 4.2.7 on 2026-05-29 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_cifras_maximas_usuario_cifras_minimas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apuestas_liquidadas', to='core.liquidacion'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='liquidacion_pagada',
            field=models.BooleanField(default=False),
        ),
    ]
