# Generated by Django 4.2.7 on 2026-05-29 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apuesta_liquidacion_apuesta_liquidacion_pagada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoLoteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_ganador', models.CharField(max_length=6)),
                ('cifras', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(limit_choices_to={'rol__in': ['admin_general', 'empresario']}, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_creados', to=settings.AUTH_USER_MODEL)),
                ('loteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.loteria')),
            ],
            options={
                'verbose_name': 'Resultado de Lotería',
                'verbose_name_plural': 'Resultados de Loterías',
                'unique_together': {('loteria', 'fecha', 'numero_ganador')},
            },
        ),
    ]
