# Generated by Django 4.2.7 on 2026-05-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resultadoloteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteria',
            name='tope_premio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
