# Generated by Django 4.2.7 on 2026-05-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_loteria_tope_premio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planpremio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='planpremio',
            name='es_combinado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planpremio',
            name='premio_por_peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='planpremio',
            unique_together={('empresario', 'loteria', 'cifras', 'es_combinado')},
        ),
        migrations.RemoveField(
            model_name='planpremio',
            name='multiplicador',
        ),
    ]
