# Generated by Django 4.2.7 on 2026-05-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_planpremio_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cifras_maximas',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cifras_minimas',
        ),
        migrations.AddField(
            model_name='usuario',
            name='autorizar_2c_combinado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='autorizar_2c_directo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='autorizar_3c_combinado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='autorizar_3c_directo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='autorizar_4c_combinado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='autorizar_4c_directo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='autorizar_5c_combinado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='autorizar_5c_directo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='autorizar_6c_combinado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='autorizar_6c_directo',
            field=models.BooleanField(default=True),
        ),
    ]
