# Generated by Django 4.2.7 on 2026-05-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_usuario_cifras_maximas_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planpremio',
            unique_together={('empresario', 'cifras', 'es_combinado')},
        ),
        migrations.RemoveField(
            model_name='planpremio',
            name='loteria',
        ),
    ]
