# Generated by Django 4.2.7 on 2026-05-30 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_planpremio_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcumuladoNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=6)),
                ('cifras', models.PositiveSmallIntegerField()),
                ('monto_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_ultima_apuesta', models.DateTimeField(auto_now=True)),
                ('empresario', models.ForeignKey(limit_choices_to={'rol': 'empresario'}, on_delete=django.db.models.deletion.CASCADE, related_name='acumulados', to=settings.AUTH_USER_MODEL)),
                ('loteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acumulados', to='core.loteria')),
            ],
            options={
                'verbose_name': 'Acumulado de Número',
                'verbose_name_plural': 'Acumulados de Números',
                'ordering': ['-monto_acumulado'],
                'unique_together': {('empresario', 'loteria', 'numero', 'cifras')},
            },
        ),
    ]
