# Generated by Django 4.2.7 on 2026-05-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_acumuladonumero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dias_retencion_datos',
            field=models.PositiveSmallIntegerField(default=90, help_text='Días a mantener datos antes de depuración automática'),
        ),
    ]
