# Generated by Django 4.2.7 on 2026-05-30 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_usuario_dias_retencion_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('chancero', models.ForeignKey(limit_choices_to={'rol': 'chancero'}, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('apuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_clientes', to='core.apuesta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Historial de Cliente',
                'verbose_name_plural': 'Historiales de Clientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['cliente', 'fecha_registro'], name='core_histor_cliente_cb0688_idx'), models.Index(fields=['apuesta'], name='core_histor_apuesta_b3b6e0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['chancero', 'telefono'], name='core_client_chancer_d39643_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['activo'], name='core_client_activo_726b6f_idx'),
        ),
    ]
