# Generated by Django 4.2.7 on 2026-06-02 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cliente_historialcliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('apuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_premio', to='core.apuesta')),
                ('pagado_por', models.ForeignKey(limit_choices_to={'rol__in': ['empresario', 'admin_general']}, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Premio',
                'verbose_name_plural': 'Pagos de Premios',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
