# Generated by Django 4.2.7 on 2026-06-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pagopremio'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='valor_empresario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
