# Generated by Django 4.2.7 on 2026-07-29 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_liquidacion_valor_empresario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(help_text='Twilio Account SID', max_length=64)),
                ('api_key_sid', models.CharField(help_text='Twilio API Key SID (empieza con SK)', max_length=64)),
                ('api_key_secret', models.CharField(help_text='Twilio API Key Secret', max_length=64)),
                ('sms_number', models.CharField(help_text='Formato E.164, ej. +12345678901', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Número de sandbox de WhatsApp, ej. whatsapp:+14155238886', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresario', models.OneToOneField(limit_choices_to={'rol': 'empresario'}, on_delete=django.db.models.deletion.CASCADE, related_name='twilio_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
