# Generated by Django 4.2.7 on 2026-07-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_twiliocredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='comision_admin_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión que cobra el Admin sobre las ventas brutas del empresario', max_digits=5),
        ),
    ]
